### ISSUE TITLE
[REQ] Add possibility to retrieve poster from Bedetheque

### ISSUE THREAD

**Issue by kesm** [Inervo/BedethequeKomga#6]
**Is your feature request related to a problem? Please describe.**
I was looking at some books parsed using your script and I noticed that some of my books have double page for the first page so it doesn't look good in Komga
![image](https://github.com/Inervo/BedethequeKomga/assets/6907912/89463165-1b2c-43b7-b7f5-bc7f27f0ebe6)

**Describe the solution you'd like**
An option to retrieve the poster would be nice

**Additional context**
I don't know if it's technically possible but it could be helpful! 
As I already parsed my library and all items have an url maybe the option should check something else to see if a poster is needed or not?

**Comment by Inervo** [comment]
Hi,

It may be possible to add a thumbnail (not sure however), but that would not be book or condition specific, but for all the books parsed by the script. 

I'm don't think that would be the ideal behavior for such specific use cases, even though I understand the objective. So I won't develop this, sorry.
For these cases, it may be easier to either upload the expected book cover manually in komga or to modify the cover in your book itself.
